# Generated by extendr: Do not edit by hand

# nolint start

#
# This file was created with the following call:
#   .Call("wrap__make_dlnm_wrappers", use_symbols = TRUE, package_name = "dlnm")

#' @usage NULL
#' @useDynLib dlnm, .registration = TRUE
NULL

#' Compute the dot product of two numeric vectors.
#' This is a trivial test function to verify the R-Rust bridge works.
#' @param x A numeric vector.
#' @param y A numeric vector of the same length as x.
#' @return A scalar numeric value representing the dot product.
rust_dot_product <- function(x, y) .Call(wrap__rust_dot_product, x, y)

#' Sum elements of a numeric vector using Rayon parallel reduction.
#' This verifies that the rayon dependency is correctly linked.
#' @param x A numeric vector.
#' @return A scalar numeric value representing the sum.
rust_parallel_sum <- function(x) .Call(wrap__rust_parallel_sum, x)


# nolint end
